Добавил навбар и немного накидал страницу пользователя
Yandex-Twin-Peaks/mega-game pull request #40
Opened 2022-06-09 15:22 UTC by Saykind93

2022-06-09 16:01 UTC, kxnkxv requested changes

2022-06-12 14:08 UTC, NightFreeze requested changes
Привет! Срасибо за пр, страница уже начинает приобретать вид.
Замечания:
1) есть небольшой комментарий в коде
2) название ветки - называй её, пожалуйста, номером назачи в начале
3) Юра настроил доску в гитхабе, мы переехали туда, обнови, пожалуйста, на ней статусы 
4) Попрошу тебя называть коммит исходя из содержания, а не из эмоциональной составляющей :) Название коммита должно отвечать на вопрос "что было сделано", чтобы это легко можно было понять.
5) Доработай, пожалуйста, страницу пользователя в соответствии с макетом https://www.figma.com/file/24EUnEHGEDNLdOcxg7ULwV/Chat?node-id=1%3A498
Пока не старайся сделать цвета и шрифты один в один, но расположения и сохранение инпутов нужно держать в локальном стейте, чтобы легко было добавить данные в запрос.

2022-06-13 16:14 UTC, NightFreeze approved these changes

2022-06-13 16:14 UTC, NightFreeze commented on src/components/organisms/UserSettings/UserSettings.tsx
> +  const [file, setFile]:any = useState(null);
Лучше типизировать поля
`const [passwords, setPasswords] = useState<IPassowords>({});`

2022-06-13 16:14 UTC, NightFreeze commented on src/components/organisms/UserSettings/UserSettings.tsx
>    const USERPASSWORDSINPUTS = ['old_password', 'new_password'];
Рада, что учитываешь предыдущие комментарии. Теперь можно улучшить читаемость и разделить такое длинное название переменной через нижнее подчёркивание
`USER_PASSWORD_INPUTS`

2022-06-13 16:14 UTC, NightFreeze commented on src/components/organisms/UserSettings/UserSettings.tsx
> +          label={inputName}
Хорошо бы на будущее называть поля так, как их ожидает увидеть бэк
https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile

2022-06-13 16:14 UTC, NightFreeze commented on src/components/organisms/UserSettings/UserSettings.tsx
> +          label={inputName}
Я увидела, ты так и сделал. Хорошо.

2022-06-13 18:47 UTC, merged